### ISSUE TITLE
panicked at src/byte_functions/mod.rs:41:17

### ISSUE THREAD

**Issue by ckcr4lyf** [ckcr4lyf/kiryuu#51]
Also happens at `57:17`.

Logs:
```
thread 'actix-rt|system:0|arbiter:0' panicked at src/byte_functions/mod.rs:57:17:
index out of bounds: the len is 40 but the index is 40
thread 'actix-rt|system:0|arbiter:0' panicked at src/byte_functions/mod.rs:41:17:
index out of bounds: the len is 40 but the index is 40
```

Code:

https://github.com/ckcr4lyf/kiryuu/blob/de06f1e4fec93ffc27bdc255b7131d652fbb0c5f/src/byte_functions/mod.rs#L40-L45

https://github.com/ckcr4lyf/kiryuu/blob/de06f1e4fec93ffc27bdc255b7131d652fbb0c5f/src/byte_functions/mod.rs#L56-L60

Should fix it probably...

**Comment by ckcr4lyf** [comment]
This can be done via a dummy magnet URL as:

```
magnet:?xt=urn:btih:4141414141414141414141414141414141414125&dn=FAKENAME&tr=http://192.168.128.128:6969/announce
```

Where `tr` is replaced with an instance of the tracker

**Comment by ckcr4lyf** [comment]
We can see at least qbittorrent encodes the final `0x25` byte of the infohash in the query param as `"%25"` (i.e. `[0x25, 0x32, 0x35]`)
